services:
  provisioner:
    build:
      context: .
      cache_from:
        - type=registry,ref=ghcr.io/unicorns/infra:buildcache
    volumes:
      - .:/${COMPOSE_PROJECT_NAME:?}:ro
      # The output directory is mounted as rw so that the provisioner can write
      # to it.
      - ./outputs:/${COMPOSE_PROJECT_NAME:?}/outputs:rw
      # The .github/workflows directory is mounted as rw so that the provisioner
      # can generate workflows.
      - ./.github/workflows:/${COMPOSE_PROJECT_NAME:?}/.github/workflows:rw
    tmpfs:
      - /run:exec
      - /tmp:exec
    working_dir: /${COMPOSE_PROJECT_NAME:?}
    # init handles singal forwarding so the container can be stopped gracefully.
    init: true
    environment:
      DRY_RUN: ${DRY_RUN:-}
      PYTHONPATH: /${COMPOSE_PROJECT_NAME:?}
